'use client';
import React from 'react';
import { Helmet } from '@/lib/helmet';
import {Link} from '@/lib/router';

export const TermsConditions = () => {
  return (
    <>
    <Helmet>
        <title>ClanConnect - Terms & Conditions</title>
        <link rel="canonical" href="https://www.clanconnect.ai/terms_conditions" />
        <meta name="robots" content="index, follow" />
        <meta property="og:url" content="https://www.clanconnect.ai/terms_condition" />
        <meta property="og:title" content="ClanConnect - Terms & Conditions" />
        <meta property="og:description" content="Clan Connect - The Most Democratic Influencer Marketing Platform of the World. Collaborate with social media influencers." />
        <meta property="og:image" content="https://clanconnect.s3.ap-south-1.amazonaws.com/static_images/web-clanconnect/terms-conditions.png" />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="627" />
      </Helmet>

    <main className='main-content-sec padd-content-top110 full-width'>
      <div className='container-fluid'>
        <div className='bg-white content-bg p-3 min-vh-100'>
          <div className='container custom-container'>
            <h3 className='title-w-bdr'>
              <span>Terms &amp; Conditions</span>
            </h3>
            <div className='content-info'>
              <p>
                This is an electronic record in accordance with Information
                Technology Act, 2000 (
                <i>
                  as may be amended, modified, re-enacted, consolidated or
                  replaced from time to time
                </i>
                ) and rules thereunder pertaining to electronic records as
                applicable and amended from time to time. This document is
                generated by a computer system and does not require any physical
                or electronic signature.
              </p>

              <p>
                This document is published in accordance with the provisions of
                Rule 3(1) of the Information Technology (
                <i>Intermediaries guidelines</i>) Rules, 2011 which mandates an
                intermediary to publish the rules and regulations, the privacy
                policy and the terms and conditions for access or usage of the
                website or an application.
              </p>

              <p>
                Services (<i>defined hereinafter</i>) offered on or through our
                Website (<i>defined hereinafter</i>) and/or use of the
                Application (<i>defined hereinafter</i>) or use of any other
                media format, you (<i>defined hereinafter</i>) accept, agree to
                comply with and be bound by this Agreement (
                <i>defined hereinafter</i>) which forms a binding Agreement
                between you and us (<i>defined hereinafter</i>). By using the
                Services, you represent and warrant that you are of legal age to
                form a binding contract with us.
              </p>

              <p>
                Therefore, your use of the Website and/ or use of the
                Application and its related services and tools are governed
                collectively by the &quot;Terms of Use, &nbsp;
                <Link to='/privacy_policy/'>Privacy Policy</Link>,&nbsp;
                <Link to='/pricing_policy'>Pricing Policy</Link>,&nbsp;
                <Link to='/refund_cancellation_policy'>
                  Cancellation &amp; Refund Policy
                </Link>
                &quot; as may be applicable.
              </p>

              <p>
                INSTALLING, SIGNING UP, ACCESSING, BROWSING OR OTHERWISE USING
                THE WEBSITE AND/ OR AN APPLICATION INDICATES YOUR AGREEMENT TO
                ALL THE TERMS AND CONDITIONS HEREIN, YOU ARE REQUESTED TO READ
                THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
              </p>

              <p>
                If you do not want to be bound by these Terms of Use, you must
                not retain, access, or use the Application and /or the Website
                in any manner whatsoever. Anything done, caused to be done,
                whether expressly or impliedly in contravention of these Terms
                of Use may render you liable for legal action.
              </p>

              <ul className='roman'>
                <li>
                  <strong>Definition</strong>
                  <p>For the purposes of the Terms and conditions:</p>
                  <ul>
                    <li>
                      <strong>“Agreement”</strong> shall mean the Terms of Use,
                      the Privacy Policy, Cancellation and Refund Policy,
                      Pricing Policy and any other policies as may be framed by
                      us from time to time.
                    </li>

                    <li>
                      <strong>“Clanconnect”</strong>, <strong>“we”</strong>,{' '}
                      <strong>“our”</strong>, <strong>“us”</strong> and{' '}
                      <strong>“Company”</strong> shall mean Irida Interactive
                      Private Limited having its registered office at 2ND FLOOR,
                      249, Okhla Phase 3 Road, Okhla Industrial Estate Phase 3,
                      New Delhi, South East Delhi, 110020, India.
                    </li>

                    <li>
                      <strong>“Platform”</strong> shall mean a collective
                      reference to the Services provided through the website at{' '}
                      <a href='/'>www.clanconnect.ai</a> or through the
                      application installed by you on your mobile device,
                      tablet, computer, etc.
                    </li>

                    <li>
                      <strong>“Services”</strong> shall include but not be
                      limited to:
                      <strong className='d-block pt-2 pb-1'>
                        With respect to Influencer:{' '}
                      </strong>
                      <ol className='pb-2'>
                        <li>
                          Apply to briefs posted by brands/Agencies and reach a
                          negotiable price.
                        </li>
                        <li>
                          Get approvals on the creatives for the campaign.
                        </li>
                        <li>One-on-one conversation with the brand/Agency.</li>
                        <li>Online creative repository.</li>
                        <li>Get analytics for the posts.</li>
                      </ol>
                      <strong className='d-block pt-2 pb-1'>
                        With respect to Brand:
                      </strong>
                      <ol>
                        <li>
                          Search for influencers based on different parameters
                          and create list.
                        </li>
                        <li>View complete insights of an influencer.</li>
                        <li>
                          Create and post the campaign briefs and get proposals
                          from the Influencers.
                        </li>
                        <li>Complete workflow for the price negotiation.</li>
                        <li>One on one conversation with the influencers.</li>
                        <li>Creative approval workflow.</li>
                        <li>Online creative repository.</li>
                        <li>
                          Get analytics for the campaign as a whole or as per
                          influencer/post.
                        </li>
                      </ol>
                      <strong className='d-block pt-2 pb-1'>
                        With respect to Agency:
                      </strong>
                      <ol className='mb-2'>
                        All the services offered to brand along with:
                        <li>Add multiple brands on the dashboard. </li>
                      </ol>
                    </li>
                    <li>
                      <strong>“Website”</strong> shall mean the website{' '}
                      <a href='https://www.clanconnect.ai'>
                        www.clanconnect.ai
                      </a>{' '}
                      of the company.
                    </li>
                    <li>
                      <strong>“You”</strong>, <strong>“Your”</strong>,{' '}
                      <strong>“your” “yourself”,“yourself”, “user“</strong> and{' '}
                      <strong>“you”</strong> shall mean the end user, who meets
                      the eligibility criteria set out below.
                    </li>
                  </ul>
                </li>
                <li>
                  <strong>Right to Use</strong>
                  <p>
                    Your right to use the Services is subject to the
                    limitations, conditions, and restrictions established by us
                    from time to time, at our sole discretion. We may alter,
                    suspend, or discontinue the Services at any time, without
                    any prior intimation to the user. We may also impose limits
                    on certain features and/ or aspects of the Services and/ or
                    restrict your access to certain parts of the Services and/
                    or all of the Services without any prior intimation and any
                    liability on us.
                  </p>
                </li>
                <li>
                  <strong>Availability of Services</strong>
                  <p>
                    By using the Platform, you acknowledge that while we take
                    every reasonable action to make sure that the Services
                    remain fully functional and up to date, interruptions do
                    happen, for any reason or no reason, including for routine
                    maintenance, as may be required for effective functioning of
                    the Platform. You understand and acknowledge that the
                    Services could be interrupted, suspended, or terminated due
                    to any reason whatsoever, without any fault of ours and
                    therefore we shall not be held liable in any manner
                    whatsoever, for any loss to anyone due to such interruption,
                    suspension, or termination of Services without any fault of
                    ours.
                  </p>
                </li>

                <li>
                  <strong>Account and Plan</strong>

                  <p>
                    To register an account with us, you will be required to fill
                    an online form on the Platform available at{' '}
                    <Link to='https://www.clanconnect.ai'>
                      https://www.clanconnect.ai
                    </Link>
                    , by providing certain details (“<strong>Form</strong>”). We
                    expect that You would complete the Form with fairness and
                    honesty while furnishing the information, as required to
                    create an account on the Platform. After filling the Form,
                    You are required to select a plan available on the Platform.
                    For more details about the plans please go through our
                    Pricing Policy, available at{' '}
                    <Link to='/pricing_policy'>
                      https://www.clanconnect.ai/pricing_policy
                    </Link>
                    .
                  </p>

                  <p>
                    Every Form filled by You shall undergo a review process by
                    our team and We reserve the right to seek such additional
                    details as may be required in order to ensure that the
                    details provided by You meet the minimum criteria as decided
                    by us. During such review process, we reserve the right to
                    suspend and/ or delete any profile/ account if we are of the
                    opinion that the required profile/ account does not meet the
                    required standards set by the Company. Further, if at any
                    point of time we come to know or have reasons to believe
                    that any information provided by you is untrue, inaccurate,
                    or incomplete then we have absolute right to suspend or
                    terminate your account and forfeit the amount paid (if any)
                    by you towards our plan fee and refuse to provide our
                    Service to you thereafter without any notice.
                  </p>

                  <p>
                    You are responsible to keep your account details up to date
                    at all times and must ensure that the password which you
                    have created on the Platform to access the account must be
                    confidential and must not disclose it to or share it with
                    anyone. You shall be responsible for all activities that
                    occur under your account. You will not sell or otherwise
                    transfer your account to any person or entity.
                  </p>

                  <p>
                    You shall be held liable for display on the Platform through
                    your account of any grossly harmful, blasphemous, obscene,
                    pornographic, pedophilic or violent display of any material
                    to minors which in anyway is hateful, or racially and
                    ethnically objectionable, disparaging, relating or
                    encouraging money laundering or gambling, false, malicious,
                    inaccurate or misleading, fraudulent in nature or involving
                    the sale of counterfeit or stolen items or items which are
                    otherwise illegal or unlawful in any manner whatsoever.
                  </p>

                  <p>
                    We reserve the right to reject, refuse to post and/or delete
                    any Service or to deny, restrict, suspend your access for
                    any reason whatsoever, including, but not limited to
                    bullying, hate speech, harassment, terrorism, negative
                    comments on the Services, which are in violation of these
                    Terms of Use or being considered to be offensive, illegal or
                    in violation of the rights of any person or entity, or being
                    harmful or threatening to the safety of others.
                  </p>

                  <p>
                    <strong>Deletion of Account : </strong> Any user wishing to
                    delete his/ her account, has to write an e-mail to us at,
                    for <strong>Brands & Advertisers,</strong>{' '}
                    <a href='mailto: brand.support@clanconnect.ai'>
                      brand.support@clanconnect.ai
                    </a>
                    , for <strong>Influencers & Talent Partners,</strong>{' '}
                    <a href='mailto: influencer.support@clanconnect.ai'>
                      influencer.support@clanconnect.ai
                    </a>
                    . The Company may within 10 (ten) business days delete your
                    account and you shall receive a confirmation e-mail from the
                    Company for the same. Further, please note that as of now
                    Company does not allow the cancellation of plan, therefore,
                    even if your account gets deleted, your plan fee will not be
                    refunded. For more details on cancellation of plan, please
                    visit our Cancellation and Refund Policy, available at
                    <Link to='/refund_cancellation_policy'>
                      https://www.clanconnect.ai/refund_cancellation_policy
                    </Link>
                    . You hereby agree to be personally liable for any and all
                    charges incurred under your username and password until your
                    account gets deleted. You acknowledge and agree that if your
                    account gets deleted, the access associated with that
                    account will be removed permanently from our database and if
                    you wish to create an account again in future, you will have
                    to follow user registration procedure again, as all the
                    previous data and information collected by us will be
                    removed permanently.
                  </p>
                </li>

                <li>
                  <strong>Intellectual Property Right</strong>
                  <p>
                    We solely own rights in the name and mark of ClanConnect and
                    the logo that appears on the Platform (the 
                    <strong>“Logo”</strong>). You are not permitted to, and you
                    agree not to, use these marks in any manner (including as
                    part of any other trademark, Company name or domain name),
                    in connection with any product or service.
                  </p>
                  <p>
                    We own and have the authorized license of all intellectual
                    property rights (including copyright) in and to the Platform
                    including intellectual property rights in the content
                    hosted, published, displayed, uploaded on the Platform by
                    us. Copyright laws and treaties throughout the world protect
                    these works and all rights in and to them are reserved by
                    us. No information, content or material from us may be
                    copied, reproduced, republished, uploaded, posted,
                    transmitted or distributed in any way without our express
                    written permission.
                  </p>
                </li>

                <li>
                  <strong>YouTube and Instagram</strong>
                  <p>
                    We use YouTube API Services. All users including
                    Influencers, Brands or agents, are agreeing to be bound by
                    YouTube’s Terms of Service (ToS){' '}
                    <a href='https://www.youtube.com/t/terms' target='_blank'>
                      https://www.youtube.com/t/terms
                    </a>{' '}
                    and Instagram’s Terms of Service
                    <a href='https://help.instagram.com/581066165581870'>
                      https://help.instagram.com/581066165581870
                    </a>
                    . Users can revoke Clanconnect’s access to their data via
                    Google, go to{' '}
                    <a
                      href='https://myaccount.google.com/permissions'
                      target='_blank'
                    >
                      https://myaccount.google.com/permissions
                    </a>
                    .
                  </p>
                </li>
                <li>
                  <strong>Dispute Resolution</strong>
                  <p>
                    If you consider there to be a dispute between you and us or
                    the services provided by us, please contact us at for{' '}
                    <strong>Brands & Advertisers,</strong>{' '}
                    <a href='mailto: brand.support@clanconnect.ai'>
                      brand.support@clanconnect.ai
                    </a>
                    , for <strong>Influencers & Talent Partners,</strong>{' '}
                    <a href='mailto: influencer.support@clanconnect.ai'>
                      influencer.support@clanconnect.ai
                    </a>
                    . These terms of use, privacy policy, pricing policy and
                    cancellation and refund policy that are available on the
                    Platform shall be governed by and construed in accordance
                    with the laws of India. You agree to submit to the exclusive
                    jurisdiction of the courts of India to resolve any dispute
                    arising out of the same. We shall not be held liable for any
                    dispute arising out of any communication led through/on our
                    Platform between any two users using the Platform. Your use
                    of the Platform is not permitted in any jurisdiction that
                    does not give effect to all provisions of the Terms,
                    including without limitation, this section.
                  </p>
                </li>
                <li>
                  <strong>Liability</strong>
                  <p>
                    The content on the Platform has been provided in good faith
                    on an “as is where is” basis without any warranty as to
                    fitness for purpose. The content may contain inaccuracies or
                    typographical errors. Whilst we endeavor to ensure that the
                    information provided by us is correct, no warranty, express
                    or implied, is given as to its accuracy and we do not accept
                    any liability for error or omission or that the functions
                    contained in Services, information and materials, including,
                    without limitation any third party sites or services linked
                    to the Platform, whether they will be uninterrupted or will
                    be conducted in a timely manner, or that the defects will be
                    rectified by us, or that the servers that make such
                    Services, content, information and materials available are
                    free of viruses or other harmful components. In using the
                    Platform, you agree that neither us nor any of our
                    employees, contractors, partners, sponsors, advertisers or
                    others, are responsible or liable for any content or items,
                    including but not limited to any text, information, images
                    including photographs or graphics, audio clips, video clips,
                    and web-links posted by you, other users, or third parties.
                    You also agree that the Company or any of its affiliates are
                    not responsible for the content or availability of third
                    party websites and/or mobile applications linked to or
                    referenced herein. You agree that Company or any of their
                    affiliates shall not be responsible or liable, directly or
                    indirectly, for any damage and/ or loss caused and/ or
                    alleged to be caused by and/ or in connection with your use
                    of and/ or reliance on any such content and/ or on the goods
                    and/ or services available on and/ or through any such
                    websites and/or mobile applications or any other matter
                    relating to the Company. Any material downloaded and/ or
                    otherwise obtained through the Platform is accessed at your
                    own risk, and you will be solely responsible for any damage
                    and/ or loss of data that results from such download to your
                    computer system, if any. We will not assure you that other
                    users are or will be complying with the foregoing rules or
                    any other provisions of these Terms, and, as between you and
                    us, you hereby assume all risk of harm or injury resulting
                    from any such lack of compliance by you. Nothing in this
                    Agreement shall limit or exclude our liability for
                    fraudulent misrepresentation, for death or personal injury
                    resulting from our negligence or the negligence of our
                    agents or employees or for any other liability that cannot
                    be limited or excluded by law.
                  </p>
                </li>
                <li>
                  <strong>Breach of these Terms</strong>
                  <p>
                    Your Account and associated plans are non-transferrable and
                    may not be sold, traded, combined, or otherwise shared with
                    any other person. If you violate any of these terms and
                    conditions, we may terminate your account at our sole
                    discretion and without limitation, either with or without
                    notice. Should we terminate your Account, we will forfeit
                    all the information and other compilations created by you
                    through the Platform, and you may not be entitled to
                    re-enroll or re-join or create a new account unless invited
                    to re-join or to register to a new account by us.
                  </p>
                  <p>
                    Upon suspension or termination of your account with us, we
                    reserve the right to remove or delete your information that
                    is available with us, including but not limited to your
                    login, account information and information posted by you.
                    The restriction, suspension or termination of your account
                    or your access to the Platform pursuant to this section will
                    be without prejudice to any rights which we may have against
                    you in respect of your breach of these Terms. Further, if
                    required by applicable law(s) or by a court order or by
                    other enforcement authorities and/ or agencies or if we in
                    our sole discretion consider the disclosure of such
                    information necessary or appropriate, we will disclose your
                    user identity and other details, as available by us.
                  </p>
                </li>
                <li>
                  <strong>Indemnification</strong>
                  <p>
                    You agree to indemnify and hold us, our directors,
                    representatives, employees and contractors, harmless from
                    any claim or demand, including reasonable solicitors fees,
                    made by any third party due to or arising out of your use of
                    the Platform, the breach of these Terms by you, or the
                    infringement by you of any intellectual property or other
                    right of any other person or entity.
                  </p>
                </li>
                <li>
                  <strong>User Warranties</strong>
                  <p>
                    By creating an account with us, or accessing information as
                    part of the Services, you warrant and agree that you: (a)
                    possess the authority to create a binding legal obligation,
                    on behalf of yourself personally, or if you are creating an
                    account in the name of an individual or entity or
                    organization, that you have the authority to do so, and are
                    not impaired in this ability; (b) that all the information
                    you provide to us is only about yourself, or the
                    account-holder entity, and that all of such information is
                    accurate, true, up-to-date, and complete; (c) your use of
                    the Service will always comply with the terms as specified
                    herein; and (d) you shall be responsible for all uses of
                    your account, safeguard your username and password, and
                    supervise the use of your account.
                  </p>
                </li>
                <li>
                  <strong>Disclaimer of Warranties</strong>
                  <p>
                    You expressly agree that your use of the Service is at your
                    sole and exclusive risk. The Services are provided on an “as
                    it is, with all faults,” and “as available” basis, without
                    warranties of any kind, including, without limitation: the
                    availability, accuracy of content or materials, information,
                    or Service, and the warranties of merchantability, fitness
                    for a particular purpose, and non-infringement. The Company
                    expressly disclaims all such warranties. The entire risk as
                    to the quality and timeliness of the information, and all
                    services provided by us is borne exclusively by you. We use
                    public data and information provided to us by third parties
                    in order to compile each “service” as such, we rely on the
                    providers of this information for its accuracy and
                    correctness. We make no warranty that the Service will meet
                    your requirements, or that the Services will be
                    uninterrupted, timely, secure, or error free; nor do we make
                    any warranty as to the results that may be obtained from the
                    use of the Service or as to the accuracy or reliability of
                    any information obtained through the Service.
                  </p>
                </li>
                <li>
                  <strong>General</strong>
                  <p>
                    If any provision of these Terms is unenforceable as
                    determined by a court of competent jurisdiction under
                    applicable law, then such provision shall be struck out. All
                    remaining provisions shall remain in full force and effect.
                    If we delay or fail to act in respect of any breach by you
                    of these Terms, this will not operate as a waiver of our
                    right to act in relation to subsequent or similar breaches
                    by you.
                  </p>
                </li>
                <li>
                  <strong>Miscellaneous</strong>
                  <p>
                    Waiver by you of any breach or default or failure to
                    exercise any right allowed hereunder constitutes a waiver of
                    any prior, or subsequent breach, or default, and a waiver or
                    forfeiture of any similar or future rights. The section
                    headings used herein are for convenience only and shall be
                    of no legal force or effect. If a court of competent
                    jurisdiction holds any provision of these terms of use
                    invalid, such invalidity shall not affect the enforceability
                    of any other provisions contained herein and the remaining
                    portions shall continue to be in full force and effect.
                    These Terms of Use, Privacy Policy, Cancellation and Refund
                    Policy and Pricing Policy constitute the sole and entire
                    agreement between you and us with respect to the Service and
                    supersede all prior and contemporaneous understandings,
                    representations, and warranties, both in written and/ or
                    oral with respect to the Services.
                  </p>
                </li>
                <li>
                  <strong>Terms and Conditions for Influencer</strong>
                  <p>
                    In addition to the above terms and conditions, the below
                    terms and conditions shall be applicable on the influencers
                    rendering Services through the Website or an Application:
                  </p>

                  <ul>
                    <li>
                      We connect through our Platform, the brands with the
                      influencers registered with us in lieu of rendering the
                      Services.
                    </li>
                    <li>
                      A list of influencers registered with us, will be
                      exhibited to the brands once they register with us on our
                      Platform.
                    </li>
                    <li>
                      Influencers should have attained 18 (eighteen) years of
                      age in order to register on Platform and render the
                      Services.
                    </li>
                    <li>
                      Influencer shall ensure that any post and/ or action on
                      social media for any brand is for promotional purposes and
                      it should not result in negative publicity for the brand.
                      Any such breach will terminate the influencer’s agreement
                      with us and shall also be liable for appropriate
                      compensation to the brand, if required.
                    </li>

                    <li>
                      Influencer while registering with us should provide
                      accurate information about all of his or her social media
                      handles and their traffic. Any misrepresentation
                      whatsoever shall result in breach of these terms and
                      conditions.
                    </li>
                    <li>
                      ClanConnect shall not be held responsible in any manner
                      for any communications (whether written or oral) between
                      the brand and the influencer. Further, influencer shall
                      ensure that he/ she shall not associate with any brand
                      outside the ClanConnect environment, in case influencer
                      does so, ClanConnect shall have the right to permanently
                      revoke the account of the influencer.
                    </li>

                    <li>
                      Influencer shall not indulge directly in any remuneration
                      or payment process with the brand and shall not in any
                      manner be associated directly with the brand, if he or she
                      is registered with us, any breach of the same could lead
                      to termination and/ or suspension of his or her account
                      with us.
                    </li>

                    <li>
                      Influencer agrees to not solicit any campaign and/ or
                      Services directly by the brand. If the influencer does
                      solicit campaigns and/ or Services with the brand, the
                      influencer’s account will be deactivated by us and he or
                      she shall not eligible for any future campaigns released
                      on the Website and Application.
                    </li>

                    <li>
                      The said engagement with the influencer is done in good
                      faith. Any manipulation including but not limited to any
                      data shared (traffic, reach) manually or through bots
                      would void any agreement of the influencer with us and no
                      payments shall be made to the influencer.
                    </li>
                  </ul>
                </li>
                <li>
                  <strong>Terms and Conditions for Brands</strong>
                  <p>
                    We are a Platform enabling brands to engage with influencers
                    and bloggers across India. A brand can select showcased and
                    registered influencers and launch a campaign with selected
                    influencer after paying the appropriate plan fee, as may be
                    specified. A brand launching a campaign agrees to the below
                    terms and conditions:
                  </p>

                  <ul>
                    <li>
                      The brand shall provide accurate information about the
                      products and services to be provided by the influencer
                      prior to engaging the influencer to render the said
                      services for the brand, and if agreed by the influencer,
                      the brand will engage the influencer to render such
                      services.
                    </li>

                    <li>
                      The brand undertakes to make the payment to us as per the
                      Pricing Policy.
                    </li>

                    <li>
                      Brand is required to pay the campaign fee to ClanConnect
                      before executing any campaign with the influencer,
                      irrespective of the plan selected by the brand{' '}
                      <em>(basic or premium)</em> as per the{' '}
                      <Link to='/pricing_policy'>Pricing Policy</Link>.
                    </li>
                    <li>
                      ClanConnect shall not be held responsible in any manner
                      for any communications (whether written or oral) between
                      the brand and the influencer. Further, brand shall ensure
                      that it shall not associate with any influencer outside
                      the ClanConnect environment, in case brand does so,
                      ClanConnect shall have the right to permanently revoke the
                      account of the brand.
                    </li>

                    <li>
                      Brand can hire influencer on contract basis for their
                      campaign and/ or Services and shall execute a contract for
                      the same with us, we shall be a facilitator between the
                      brand and the influencer.
                    </li>

                    <li>
                      We shall not be responsible or liable for any post or blog
                      or Service rendered by the influencer, which has affected
                      the brand image negatively and has been approved by the
                      brand or its agents or any of its representative.
                    </li>

                    <li>
                      The brand shall not provide any false or incorrect
                      information either to us or to the influencer.
                    </li>

                    <li>
                      The payment shall be made as per the type of campaign,
                      timeline &amp; terms stated by the influencer.
                    </li>

                    <li>
                      All applicable taxes with respect to the Services shall be
                      paid by the brand.
                    </li>
                  </ul>
                </li>
                <li>
                  <strong>Contact us</strong>
                  <p>
                    If you need to contact us for anything, you must write to us
                    at for <strong>Brands & Advertisers,</strong>{' '}
                    <a href='mailto: brand.support@clanconnect.ai'>
                      brand.support@clanconnect.ai
                    </a>
                    , for <strong>Influencers & Talent Partners,</strong>{' '}
                    <a href='mailto: influencer.support@clanconnect.ai'>
                      influencer.support@clanconnect.ai
                    </a>
                    .
                  </p>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </main>
    </>
  );
};
