import demoImg from "assets/images/project1.jpg";
import influencer from "assets/images/influencer.jpg";
export const languages = [
  { name: "Afrikaans", value: "af" },
  { name: "Amharic", value: "am" },
  { name: "Arabic", value: "ar" },
  { name: "Assamese", value: "as" },
  { name: "Azerbaijani", value: "az" },
  { name: "Belarusian", value: "be" },
  { name: "Bulgarian", value: "bg" },
  { name: "Bangla", value: "bn" },
  { name: "Bosnian", value: "bs" },
  { name: "Catalan", value: "ca" },
  { name: "Czech", value: "cs" },
  { name: "Danish", value: "da" },
  { name: "German", value: "de" },
  { name: "Greek", value: "el" },
  { name: "English (United Kingdom)", value: "en-GB" },
  { name: "English (India)", value: "en-IN" },
  { name: "English", value: "en" },
  { name: "Spanish", value: "es" },
  { name: "Spanish (Latin America)", value: "es-419" },
  { name: "Spanish (United States)", value: "es-US" },
  { name: "Estonian", value: "et" },
  { name: "Basque", value: "eu" },
  { name: "Persian", value: "fa" },
  { name: "Finnish", value: "fi" },
  { name: "Filipino", value: "fil" },
  { name: "French (Canada)", value: "fr-CA" },
  { name: "French", value: "fr" },
  { name: "Galician", value: "gl" },
  { name: "Gujarati", value: "gu" },
  { name: "Hindi", value: "hi" },
  { name: "Croatian", value: "hr" },
  { name: "Hungarian", value: "hu" },
  { name: "Armenian", value: "hy" },
  { name: "Indonesian", value: "id" },
  { name: "Icelandic", value: "is" },
  { name: "Italian", value: "it" },
  { name: "Hebrew", value: "iw" },
  { name: "Japanese", value: "ja" },
  { name: "Georgian", value: "ka" },
  { name: "Kazakh", value: "kk" },
  { name: "Khmer", value: "km" },
  { name: "Kannada", value: "kn" },
  { name: "Korean", value: "ko" },
  { name: "Kyrgyz", value: "ky" },
  { name: "Lao", value: "lo" },
  { name: "Lithuanian", value: "lt" },
  { name: "Latvian", value: "lv" },
  { name: "Macedonian", value: "mk" },
  { name: "Malayalam", value: "ml" },
  { name: "Mongolian", value: "mn" },
  { name: "Marathi", value: "mr" },
  { name: "Malay", value: "ms" },
  { name: "Burmese", value: "my" },
  { name: "Norwegian", value: "no" },
  { name: "Nepali", value: "ne" },
  { name: "Dutch", value: "nl" },
  { name: "Odia", value: "or" },
  { name: "Punjabi", value: "pa" },
  { name: "Polish", value: "pl" },
  { name: "Portuguese", value: "pt" },
  { name: "Portuguese (Portugal)", value: "pt-PT" },
  { name: "Romanian", value: "ro" },
  { name: "Russian", value: "ru" },
  { name: "Sinhala", value: "si" },
  { name: "Slovak", value: "sk" },
  { name: "Slovenian", value: "sl" },
  { name: "Albanian", value: "sq" },
  { name: "Serbian (Latin)", value: "sr-Latn" },
  { name: "Serbian", value: "sr" },
  { name: "Swedish", value: "sv" },
  { name: "Swahili", value: "sw" },
  { name: "Tamil", value: "ta" },
  { name: "Telugu", value: "te" },
  { name: "Thai", value: "th" },
  { name: "Turkish", value: "tr" },
  { name: "Ukrainian", value: "uk" },
  { name: "Urdu", value: "ur" },
  { name: "Uzbek", value: "uz" },
  { name: "Vietnamese", value: "vi" },
  { name: "Chinese (China)", value: "zh-CN" },
  { name: "Chinese (Hong Kong)", value: "zh-HK" },
  { name: "Chinese (Taiwan)", value: "zh-TW" },
  { name: "Zulu", value: "zu" },
];

export const countries = [
  { name: "Afghanistan", code: "AF" },
  { name: "Åland Islands", code: "AX" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "American Samoa", code: "AS" },
  { name: "AndorrA", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Anguilla", code: "AI" },
  { name: "Antarctica", code: "AQ" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Aruba", code: "AW" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bermuda", code: "BM" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Bouvet Island", code: "BV" },
  { name: "Brazil", code: "BR" },
  { name: "British Indian Ocean Territory", code: "IO" },
  { name: "Brunei Darussalam", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Cape Verde", code: "CV" },
  { name: "Cayman Islands", code: "KY" },
  { name: "Central African Republic", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Christmas Island", code: "CX" },
  { name: "Cocos (Keeling) Islands", code: "CC" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Congo", code: "CG" },
  { name: "Congo, The Democratic Republic of the", code: "CD" },
  { name: "Cook Islands", code: "CK" },
  { name: "Costa Rica", code: "CR" },
  { name: 'Cote D"Ivoire', code: "CI" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Cyprus", code: "CY" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Ethiopia", code: "ET" },
  { name: "Falkland Islands (Malvinas)", code: "FK" },
  { name: "Faroe Islands", code: "FO" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "French Guiana", code: "GF" },
  { name: "French Polynesia", code: "PF" },
  { name: "French Southern Territories", code: "TF" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Gibraltar", code: "GI" },
  { name: "Greece", code: "GR" },
  { name: "Greenland", code: "GL" },
  { name: "Grenada", code: "GD" },
  { name: "Guadeloupe", code: "GP" },
  { name: "Guam", code: "GU" },
  { name: "Guatemala", code: "GT" },
  { name: "Guernsey", code: "GG" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Heard Island and Mcdonald Islands", code: "HM" },
  { name: "Holy See (Vatican City State)", code: "VA" },
  { name: "Honduras", code: "HN" },
  { name: "Hong Kong", code: "HK" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran, Islamic Republic Of", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Isle of Man", code: "IM" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jersey", code: "JE" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: 'Korea, Democratic People"S Republic of', code: "KP" },
  { name: "Korea, Republic of", code: "KR" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: 'Lao People"S Democratic Republic', code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libyan Arab Jamahiriya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Macao", code: "MO" },
  { name: "Macedonia, The Former Yugoslav Republic of", code: "MK" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Martinique", code: "MQ" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mayotte", code: "YT" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia, Federated States of", code: "FM" },
  { name: "Moldova, Republic of", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montserrat", code: "MS" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL" },
  { name: "Netherlands Antilles", code: "AN" },
  { name: "New Caledonia", code: "NC" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "Niue", code: "NU" },
  { name: "Norfolk Island", code: "NF" },
  { name: "Northern Mariana Islands", code: "MP" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestinian Territory, Occupied", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Pitcairn", code: "PN" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Puerto Rico", code: "PR" },
  { name: "Qatar", code: "QA" },
  { name: "Reunion", code: "RE" },
  { name: "Romania", code: "RO" },
  { name: "Russian Federation", code: "RU" },
  { name: "Rwanda", code: "RW" },
  { name: "Saint Helena", code: "SH" },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Pierre and Miquelon", code: "PM" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia and Montenegro", code: "CS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Georgia and the South Sandwich Islands", code: "GS" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Svalbard and Jan Mayen", code: "SJ" },
  { name: "Swaziland", code: "SZ" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syrian Arab Republic", code: "SY" },
  { name: "Taiwan, Province of China", code: "TW" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania, United Republic of", code: "TZ" },
  { name: "Thailand", code: "TH" },
  { name: "Timor-Leste", code: "TL" },
  { name: "Togo", code: "TG" },
  { name: "Tokelau", code: "TK" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Turks and Caicos Islands", code: "TC" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" },
  { name: "United States Minor Outlying Islands", code: "UM" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Venezuela", code: "VE" },
  { name: "Viet Nam", code: "VN" },
  { name: "Virgin Islands, British", code: "VG" },
  { name: "Virgin Islands, U.S.", code: "VI" },
  { name: "Wallis and Futuna", code: "WF" },
  { name: "Western Sahara", code: "EH" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
];
export const commentData = [
  {
    id: 1,
    username: "Brand",
    date: "Jan 19",
    userComment:
      "Lorem ipsum dolor sit amet consetetur sadipscing elitr sed diam dolor sit amet consetetur sadipscing elitr sed diam adipscing elitr sed diam dolor sit amet consetetur sadipscing elitr sed diam ",
  },
  {
    id: 2,
    username: "Influencer",
    date: "Jan 29",
    userComment:
      "Lorem ipsum dolor sit amet consetetur sadipscing elitr sed diam dolor sit amet consetetur sadipscing elitr sed diam ",
  },
  {
    id: 3,
    username: "Influencer",
    date: "Jan 29",
    userComment:
      "Lorem ipsum dolor sit amet consetetur sadipscing elitr sed diam dolor sit amet consetetur sadipscing elitr sed diam ",
  },
  {
    id: 4,
    username: "Influencer",
    date: "Jan 29",
    userComment:
      "Lorem ipsum dolor sit amet consetetur sadipscing elitr sed diam dolor sit amet consetetur sadipscing elitr sed diam ",
  },
  {
    id: 5,
    username: "Influencer",
    date: "Jan 29",
    userComment:
      "Lorem ipsum dolor sit amet consetetur sadipscing elitr sed diam dolor sit amet consetetur sadipscing elitr sed diam ",
  },
  {
    id: 6,
    username: "Influencer",
    date: "Jan 29",
    userComment:
      "Lorem ipsum dolor sit amet consetetur sadipscing elitr sed diam dolor sit amet consetetur sadipscing elitr sed diam ",
  },
  {
    id: 7,
    username: "Influencer",
    date: "Jan 29",
    userComment:
      "Lorem ipsum dolor sit amet consetetur sadipscing elitr sed diam dolor sit amet consetetur sadipscing elitr sed diam ",
  },
  {
    id: 8,
    username: "Influencer",
    date: "Jan 29",
    userComment:
      "Lorem ipsum dolor sit amet consetetur sadipscing elitr sed diam dolor sit amet consetetur sadipscing elitr sed diam ",
  },
  {
    id: 9,
    username: "Influencer",
    date: "Jan 29",
    userComment:
      "Lorem ipsum dolor sit amet consetetur sadipscing elitr sed diam dolor sit amet consetetur sadipscing elitr sed diam ",
  },
  {
    id: 10,
    username: "Influencer",
    date: "Jan 29",
    userComment:
      "Lorem ipsum dolor sit amet consetetur sadipscing elitr sed diam dolor sit amet consetetur sadipscing elitr sed diam ",
  },
  {
    id: 11,
    username: "Influencer",
    date: "Jan 29",
    userComment:
      "Lorem ipsum dolor sit amet consetetur sadipscing elitr sed diam dolor sit amet consetetur sadipscing elitr sed diam ",
  },
  {
    id: 12,
    username: "Influencer",
    date: "Jan 29",
    userComment:
      "Lorem ipsum dolor sit amet consetetur sadipscing elitr sed diam dolor sit amet consetetur sadipscing elitr sed diam ",
  },
  {
    id: 13,
    username: "Influencer",
    date: "Jan 29",
    userComment:
      "Lorem ipsum dolor sit amet consetetur sadipscing elitr sed diam dolor sit amet consetetur sadipscing elitr sed diam ",
  },
  {
    id: 14,
    username: "Influencer",
    date: "Jan 29",
    userComment:
      "Lorem ipsum dolor sit amet consetetur sadipscing elitr sed diam dolor sit amet consetetur sadipscing elitr sed diam ",
  },

  {
    id: 15,
    username: "Influencer",
    date: "Jan 29",
    userComment:
      "Lorem ipsum dolor sit amet consetetur sadipscing elitr sed diam dolor sit amet consetetur sadipscing elitr sed diam ",
  },
  {
    id: 16,
    username: "Influencer",
    date: "Jan 29",
    userComment:
      "Lorem ipsum dolor sit amet consetetur sadipscing elitr sed diam dolor sit amet consetetur sadipscing elitr sed diam ",
  },
  {
    id: 17,
    username: "Influencer",
    date: "Jan 29",
    userComment:
      "Lorem ipsum dolor sit amet consetetur sadipscing elitr sed diam dolor sit amet consetetur sadipscing elitr sed diam ",
  },
];

export const commentDataInfluencer = [];

export const influncerNameDataApproved = [
  {
    name: "Influencer Name 1",
    imgData: [
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
    ],
  },
];

export const influncerNameDataPending = [
  {
    name: "Influencer Name 1",
    novideo: false,
    imgData: [
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
    ],
  },

  {
    name: "Influencer Name 2",
    novideo: false,
    imgData: [
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
    ],
  },

  {
    name: "Influencer Name 3",
    novideo: false,
    imgData: [
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
    ],
  },
];

export const influncerNameDataRejected = [
  {
    name: "Influencer Name 1",
    novideo: false,
    imgData: [
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
    ],
  },

  {
    name: "Influencer Name 2",
    novideo: false,
    imgData: [
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
    ],
  },

  {
    name: "Influencer Name 3",
    novideo: false,
    imgData: [
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
    ],
  },
];

export const compaignData = [
  {
    name: "Campaign name Two",
    img: influencer,
    imgData: [
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
    ],
  },

  {
    name: "Campaign name Two",
    img: influencer,
    imgData: [
      {
        demoImag: demoImg,
        date: "20/12/2020",
      },
    ],
  },
];
